from __future__ import annotations

from pathlib import Path
from typing import Any

from kpdl_preprocess.utils import ensure_dir


def write_qualitative_report(
    path: str | Path,
    dataset: str,
    index_records: list[dict[str, Any]],
    alert_records: list[dict[str, Any]],
    video_records: list[dict[str, Any]],
    stats: dict[str, Any],
) -> None:
    report_path = Path(path)
    ensure_dir(report_path.parent)
    lines: list[str] = []

    lines.append(f"# Qualitative Visualization Report - {dataset}")
    lines.append("")
    lines.append("Generated by SPEC 4 visualization.")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- Dataset: `{dataset}`")
    lines.append(f"- Output dir: `{stats.get('output_dir', '')}`")
    lines.append(f"- Images written: `{stats.get('num_images_written', 0)}`")
    lines.append(f"- Videos written: `{stats.get('num_videos_written', 0)}`")
    lines.append(f"- Missing frames: `{len(stats.get('missing_frames', []))}`")
    lines.append(f"- Missing cell score frames: `{len(stats.get('missing_cell_score_frames', []))}`")
    lines.append("")

    _append_top_frames(lines, index_records)
    _append_alerts(lines, index_records, alert_records)
    _append_videos(lines, video_records)

    lines.append("## Manual Review Notes")
    lines.append("")
    lines.append("Use `true_positive`, `false_positive`, or `uncertain` in the manual label column.")
    lines.append("")
    report_path.write_text("\n".join(lines), encoding="utf-8")


def _append_top_frames(lines: list[str], index_records: list[dict[str, Any]]) -> None:
    rows = [record for record in index_records if record.get("selection_type") == "top_frame"]
    rows.sort(key=lambda item: int(item.get("rank", 0)))
    lines.append("## Top Anomaly Frames")
    lines.append("")
    lines.append("| Rank | Video | Frame | Score | Severity | Top cells | Image | Manual label | Notes |")
    lines.append("| ---: | --- | ---: | ---: | --- | --- | --- | --- | --- |")
    if not rows:
        lines.append("| - | - | - | - | - | - | - | TBD | TBD |")
    for record in rows:
        lines.append(
            "| {rank} | {video_id} | {frame_id} | {score:.3f} | {severity} | {cells} | {image} | TBD | TBD |".format(
                rank=record.get("rank", ""),
                video_id=record.get("video_id", ""),
                frame_id=record.get("frame_id", ""),
                score=float(record.get("smoothed_frame_score", 0.0)),
                severity=record.get("severity", ""),
                cells=", ".join(record.get("top_cells", [])),
                image=_markdown_link(record),
            )
        )
    lines.append("")


def _append_alerts(
    lines: list[str],
    index_records: list[dict[str, Any]],
    alert_records: list[dict[str, Any]],
) -> None:
    image_by_alert = {
        str(record.get("alert_id")): record
        for record in index_records
        if record.get("selection_type") == "alert_peak"
    }
    lines.append("## Alert Segments")
    lines.append("")
    lines.append("| Alert | Video | Range | Peak frame | Score | Severity | Top cells | Reasons | Image | Manual label | Notes |")
    lines.append("| --- | --- | --- | ---: | ---: | --- | --- | --- | --- | --- | --- |")
    if not alert_records:
        lines.append("| - | - | - | - | - | - | - | - | - | TBD | TBD |")
    for alert in alert_records:
        alert_id = str(alert.get("alert_id", ""))
        image_record = image_by_alert.get(alert_id, {})
        lines.append(
            "| {alert_id} | {video_id} | {start}-{end} | {peak} | {score:.3f} | {severity} | {cells} | {reasons} | {image} | TBD | TBD |".format(
                alert_id=alert_id,
                video_id=alert.get("video_id", ""),
                start=alert.get("start_frame_id", ""),
                end=alert.get("end_frame_id", ""),
                peak=image_record.get("frame_id", ""),
                score=float(alert.get("max_score", 0.0)),
                severity=alert.get("severity", ""),
                cells=", ".join(alert.get("top_cells", [])),
                reasons="<br>".join(alert.get("reasons", [])),
                image=_markdown_link(image_record) if image_record else "-",
            )
        )
    lines.append("")


def _append_videos(lines: list[str], video_records: list[dict[str, Any]]) -> None:
    lines.append("## Overlay Videos")
    lines.append("")
    lines.append("| Video | Frames written | Path |")
    lines.append("| --- | ---: | --- |")
    if not video_records:
        lines.append("| - | - | - |")
    for record in video_records:
        path = str(record.get("relative_path") or record.get("video_path") or "")
        lines.append(f"| {record.get('video_id', '')} | {record.get('frames_written', 0)} | `{path}` |")
    lines.append("")


def _markdown_link(record: dict[str, Any]) -> str:
    path = str(record.get("relative_path") or record.get("image_path") or "")
    if not path:
        return "-"
    label = Path(path).name
    return f"[{label}]({path.replace(' ', '%20')})"
